name: Build Android APK (Debug)

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable (if exists)
        run: chmod +x ./gradlew || echo "gradlew not found, using system gradle"

      - name: Check available Gradle tasks
        run: |
          echo "Listing available Gradle tasks..."
          if [ -f "./gradlew" ]; then
            ./gradlew tasks --all || true
          else
            gradle tasks --all || true
          fi

      - name: Build Debug APK
        run: |
          echo "Starting build process..."
          if [ -f "./gradlew" ]; then
            ./gradlew :app:assembleDebug --stacktrace --info
          else
            gradle :app:assembleDebug --stacktrace --info
          fi

      - name: Upload APK artifact (if exists)
        if: success() || always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
